// packages/artplayer-template/react.js/src/App.js
import React from "react";
import Artplayer from "./ArtPlayer";

function App() {
  return (
    <div>
      <Artplayer
        option={{
          url: "https://artplayer.org/assets/sample/video.mp4",
          autoSize: true,
        }}
        style={{
          width: "600px",
          height: "400px",
          margin: "60px auto 0",
        }}
        getInstance={(art) => console.log(art)}
      />
    </div>
  );
}

export default App;

// packages/artplayer-template/vue2.js/src/App.vue
<template>
    <Artplayer @get-instance="getInstance" :option="option" :style="style" />
</template>

<script>
import Artplayer from './Artplayer.vue';

export default {
    data() {
        return {
            option: {
                url: 'https://artplayer.org/assets/sample/video.mp4',
                autoSize: true,
            },
            style: {
                width: '600px',
                height: '400px',
                margin: '60px auto 0',
            },
        };
    },
    components: {
        Artplayer,
    },
    methods: {
        getInstance(art) {
            console.log(art);
        },
    },
};
</script>
