// example/react.js/src/App.tsx
import type Artplayer from 'artplayer'
import type { Option } from 'artplayer'
import Player from './Player'

function getInstance(art: Artplayer) {
  // eslint-disable-next-line no-console
  console.log(art)
}

const style = {
  width: '800px',
  height: '600px',
  margin: '60px auto 0',
}

const option: Partial<Option> = {
  url: 'https://artplayer.org/assets/sample/video.mp4',
  autoSize: true,
}

function App() {
  return (
    <div>
      <Player
        style={style}
        option={option}
        getInstance={getInstance}
      />
    </div>
  )
}

export default App

// packages/artplayer-template/vue.js/src/App.vue
<script setup>
import { reactive } from 'vue'
import Artplayer from './Artplayer.vue'

const option = reactive({
  url: 'https://artplayer.org/assets/sample/video.mp4',
  autoSize: true,
})

const style = reactive({
  width: '600px',
  height: '400px',
  margin: '60px auto 0',
})

function getInstance(art) {
  // eslint-disable-next-line no-console
  console.log(art)
}
</script>

<template>
  <Artplayer :option="option" :style="style" @get-instance="getInstance" />
</template>
