// packages/artplayer-template/react.js/src/App.js
import React from "react";
import Artplayer from "./ArtPlayer";

function App() {
  return (
    <div>
      <Artplayer
        option={{
          url: "https://artplayer.org/assets/sample/video.mp4",
          autoSize: true,
        }}
        style={{
          width: "600px",
          height: "400px",
          margin: "60px auto 0",
        }}
        getInstance={(art) => console.log(art)}
      />
    </div>
  );
}

export default App;

// example/vue.js/src/App.vue
<script setup lang="ts">
import { reactive } from 'vue'
import Artplayer, { type Option } from 'artplayer'
import Player from './Player.vue'

const option = reactive<Partial<Option>>({
  url: 'https://artplayer.org/assets/sample/video.mp4',
  autoSize: true,
})

const style = reactive({
  width: '800px',
  height: '600px',
  margin: '60px auto 0',
})

function getInstance(art: Artplayer) {
  console.log('Artplayer instance:', art)
}
</script>

<template>
  <Player :option="option" :style="style" @get-instance="getInstance" />
</template>
